### ISSUE TITLE
Difficulties in using Automation Test Codeunit Library

### ISSUE THREAD

**Issue by shalu712** [AntonLehmus/my_blog#10]
Hi Team, I am using NAV 2018 CU2 NA version . While I am creating Test Code unit by using available Libraries getting below 
message: 'The type or method 'GenerateRandomCode' cannot be used for 'Extension' development.'
Please find below the functions which I am using via libraries but unable to do so because of errors:
- LibraryUtility.GenerateRandomCode
-LibraryInventory.CreateItem
-LibraryInventory.CreateNonStock
-Assert.AreEqual

Please suggest how to proceed further in test case in AL environment.

**Comment by AntonLehmus** [comment]
seems to be bot
